

language: go

go:
  - tip
  - 1.5
  - 1.4

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y libpcap-dev

install:
 - go get -v -t ./

script:
 - go test -v ./
 - go test -v ./logging
 - go test -v ./blocks
 - go test -v ./types
